=== toreleon/mainframe-env/conformance/0.2/schemas/release-sbom.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://mainframe-env.invalid/schemas/release-sbom@1",
  "title": "mainframe-env CycloneDX release SBOM",
  "type": "object",
  "required": ["bomFormat", "specVersion", "version", "metadata", "components"],
  "properties": {
    "bomFormat": {"const": "CycloneDX"},
    "specVersion": {"const": "1.6"},
    "version": {"type": "integer", "minimum": 1},
    "metadata": {"type": "object"},
    "components": {"type": "array", "minItems": 1}
  }
}

=== toreleon/mainframe-env/release/0.1.0-alpha.0/sbom.cdx.json
{
  "bomFormat": "CycloneDX",
  "components": [
    {
      "bom-ref": "pkg:cargo/allocator-api2@0.2.21",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "allocator-api2",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/allocator-api2@0.2.21",
      "type": "library",
      "version": "0.2.21"
    },
    {
      "bom-ref": "pkg:cargo/anstyle@1.0.14",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "anstyle",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/anstyle@1.0.14",
      "type": "library",
      "version": "1.0.14"
    },
    {
      "bom-ref": "pkg:cargo/arc-swap@1.9.2",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "arc-swap",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/arc-swap@1.9.2",
      "type": "library",
      "version": "1.9.2"
    },
    {
      "bom-ref": "pkg:cargo/argon2@0.6.0",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "argon2",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/argon2@0.6.0",
      "type": "library",
      "version": "0.6.0"
    },
    {
      "bom-ref": "pkg:cargo/atoi@2.0.0",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "name": "atoi",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/atoi@2.0.0",
      "type": "library",
      "version": "2.0.0"
    },
    {
      "bom-ref": "pkg:cargo/atomic-waker@1.1.2",
      "licenses": [
        {
          "expression": "Apache-2.0 OR MIT"
        }
      ],
      "name": "atomic-waker",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/atomic-waker@1.1.2",
      "type": "library",
      "version": "1.1.2"
    },
    {
      "bom-ref": "pkg:cargo/autocfg@1.5.1",
      "licenses": [
        {
          "expression": "Apache-2.0 OR MIT"
        }
      ],
      "name": "autocfg",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/autocfg@1.5.1",
      "type": "library",
      "version": "1.5.1"
    },
    {
      "bom-ref": "pkg:cargo/axum@0.8.9",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "name": "axum",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/axum@0.8.9",
      "type": "library",
      "version": "0.8.9"
    },
    {
      "bom-ref": "pkg:cargo/axum-core@0.5.6",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "name": "axum-core",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/axum-core@0.5.6",
      "type": "library",
      "version": "0.5.6"
    },
    {
      "bom-ref": "pkg:cargo/axum-server@0.8.0",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "name": "axum-server",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/axum-server@0.8.0",
      "type": "library",
      "version": "0.8.0"
    },
    {
      "bom-ref": "pkg:cargo/base64@0.22.1",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "base64",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/base64@0.22.1",
      "type": "library",
      "version": "0.22.1"
    },
    {
      "bom-ref": "pkg:cargo/base64ct@1.8.3",
      "licenses": [
        {
          "expression": "Apache-2.0 OR MIT"
        }
      ],
      "name": "base64ct",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/base64ct@1.8.3",
      "type": "library",
      "version": "1.8.3"
    },
    {
      "bom-ref": "pkg:cargo/bit-set@0.8.0",
      "licenses": [
        {
          "expression": "Apache-2.0 OR MIT"
        }
      ],
      "name": "bit-set",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/bit-set@0.8.0",
      "type": "library",
      "version": "0.8.0"
    },
    {
      "bom-ref": "pkg:cargo/bit-vec@0.8.0",
      "licenses": [
        {
          "expression": "Apache-2.0 OR MIT"
        }
      ],
      "name": "bit-vec",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/bit-vec@0.8.0",
      "type": "library",
      "version": "0.8.0"
    },
    {
      "bom-ref": "pkg:cargo/bitflags@2.13.1",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "bitflags",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/bitflags@2.13.1",
      "type": "library",
      "version": "2.13.1"
    },
    {
      "bom-ref": "pkg:cargo/blake2@0.11.0",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "blake2",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/blake2@0.11.0",
      "type": "library",
      "version": "0.11.0"
    },
    {
      "bom-ref": "pkg:cargo/block-buffer@0.10.4",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "block-buffer",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/block-buffer@0.10.4",
      "type": "library",
      "version": "0.10.4"
    },
    {
      "bom-ref": "pkg:cargo/block-buffer@0.12.1",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "block-buffer",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/block-buffer@0.12.1",
      "type": "library",
      "version": "0.12.1"
    },
    {
      "bom-ref": "pkg:cargo/bumpalo@3.20.3",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "bumpalo",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/bumpalo@3.20.3",
      "type": "library",
      "version": "3.20.3"
    },
    {
      "bom-ref": "pkg:cargo/byteorder@1.5.0",
      "licenses": [
        {
          "expression": "Unlicense OR MIT"
        }
      ],
      "name": "byteorder",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/byteorder@1.5.0",
      "type": "library",
      "version": "1.5.0"
    },
    {
      "bom-ref": "pkg:cargo/bytes@1.12.1",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "name": "bytes",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/bytes@1.12.1",
      "type": "library",
      "version": "1.12.1"
    },
    {
      "bom-ref": "pkg:cargo/cc@1.4.4",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "cc",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/cc@1.4.4",
      "type": "library",
      "version": "1.4.4"
    },
    {
      "bom-ref": "pkg:cargo/cfg-if@1.0.4",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
      "name": "cfg-if",
      "properties": [
        {
          "name": "cargo:source",
          "value": "registry+https://github.com/rust-lang/crates.io-index"
        }
      ],
      "purl": "pkg:cargo/cfg-if@1.0.4",
      "type": "library",
      "version": "1.0.4"
    },
    {
      "bom-ref": "pkg:cargo/chacha20@0.10.2",
      "licenses": [
        {
          "expression": "MIT OR Apache-2.0"
        }
      ],
